New feature/update post
MikaMunterud/travelFlow-server pull request #12
Opened 2023-04-14 10:09 UTC by TereseBo

Added imports, validation and controller for updatePost endpoint

2023-04-14 20:51 UTC, MikaMunterud requested changes

2023-04-14 20:51 UTC, MikaMunterud commented on src/controllers/postsRoute/addPost.js
Ser bra och tydligare ut

2023-04-14 20:51 UTC, MikaMunterud commented on src/controllers/validations/validatePost.js
> +    id: joi.string().length(24).optional()
Är id alltid 24 tecken långa? Varför är det optional?

2023-04-14 20:51 UTC, MikaMunterud commented on src/routes/postsRoute.js
Ser bra ut

2023-04-14 20:51 UTC, MikaMunterud commented on src/controllers/postsRoute/updatePost.js
> +    if(!id){
Varför valideras inte id i validate body? Om den valideras där känns det onödigt att ha denna extra check.

2023-04-14 20:51 UTC, MikaMunterud commented on src/controllers/postsRoute/updatePost.js
> +        if(result.modifiedCount==1){
Borde detta vara 3 likhetstecken?

2023-04-15 17:27 UTC, MikaMunterud commented on src/controllers/validations/validatePost.js
> +    id: joi.string().length(24).optional()
Läste lite MongoDB dokumentation, om id valideringen ska vara kvar behöver man lägga till en .hex() som en extra åtgärd för att även vara säker på att formatet är rätt.

2023-04-17 07:05 UTC, TereseBo commented on src/controllers/validations/validatePost.js
> +    id: joi.string().length(24).optional()
Det är optional för att vi använder samma validering vid post creation, men i det fallet plockas inte id-numret ut om det finns utan ett nytt genereras av db. 
-hex() tillagt.

2023-04-17 07:09 UTC, TereseBo commented on src/controllers/postsRoute/updatePost.js
> +    if(!id){
Vad menar du? ID är validerat, validatedBody är en variabel? Men om i funktionen måste vi  ha ID men det är optional i postSchema eftersom det inte behövs i addPost som använder samma schema?

2023-04-17 07:15 UTC, TereseBo commented on src/controllers/postsRoute/updatePost.js
> +        if(result.modifiedCount==1){
Åtgärdat

2023-04-18 08:15 UTC, MikaMunterud commented on src/controllers/validations/validatePost.js
> +    id: joi.string().hex().length(24).optional()
Tycker det är bättre att om en validering man har kopplat till en endpoint kräver att att postText och id finns, att validering kräver det också. Är väll bättre med en till validering som har det som krav än att behöva kolla upp det i efterhand sen igen.

2023-04-18 08:39 UTC, TereseBo commented on src/controllers/validations/validatePost.js
> +    id: joi.string().hex().length(24).optional()
Det framgick både första och andra gången du skrev det.

2023-04-18 11:22 UTC, MikaMunterud approved these changes

2023-04-18 11:31 UTC, merged