Created endpoint for followUsers & Some Validation for the endpoints
MikaMunterud/travelFlow-server pull request #13
Opened 2023-04-15 15:03 UTC by johanbacklin

Håller på med tester till denna med! Gjorde en follow och en followers om man skulle vilja använda det sen på client sidan!!

Trevlig Helg!

2023-04-15 15:34 UTC, MikaMunterud requested changes

2023-04-15 15:34 UTC, MikaMunterud commented on src/server/server.js
> +server.use("/posts", postsRoute);
Tror jag har lagt in den i min senaste pull request också, vet inte om det kan bli en konflikt senare men den behövs iaf 😊

2023-04-15 15:34 UTC, MikaMunterud commented on src/controllers/validations/validateFollow.js
> +    username: joi.string().required(),
Kanske borde lägga till en min/ max som vi har på de andra? 😊

2023-04-15 15:34 UTC, MikaMunterud commented on src/controllers/followingRoute/followUser.js
> +        await db.users.updateOne(
Är nog bra att försöka minska antalet databas requests. Skickat ett exempelmeddelande på hur man kanske kan göra 😊

2023-04-15 15:34 UTC, MikaMunterud commented on src/controllers/followingRoute/followUser.js
> +  const validatedBody = validateFollow(req.body);
username är unika i databasen, vet inte om det är nödvändigt att kolla både username och id?

2023-04-15 15:34 UTC, MikaMunterud commented on src/controllers/followingRoute/unFollowUser.js
> +
Vi ska inte kunna ta bort en person som en användare följer?

2023-04-15 17:34 UTC, johanbacklin commented on src/controllers/validations/validateFollow.js
> +    username: joi.string().required(),
Jo, har inte kollat på den. Lägger till det!

2023-04-15 17:36 UTC, johanbacklin commented on src/controllers/followingRoute/unFollowUser.js
> +
Den ligger i en annan pull request, fråga mig inte varför haha. Fick något hjärnsläpp 😂🤟🏻

2023-04-15 17:38 UTC, johanbacklin commented on src/controllers/followingRoute/followUser.js
> +  const validatedBody = validateFollow(req.body);
Gjorde koden först på id, sen såg jag att det var unikt på username…så det hamnade med!

2023-04-18 07:47 UTC, MikaMunterud approved these changes
Godkänner efter att ha kikat på problemen tillsammans på distans och fixat dem.

2023-04-18 07:47 UTC, merged