New feature/get all users
MikaMunterud/travelFlow-server pull request #18
Opened 2023-04-17 12:38 UTC by andreas8151

skapar get-all-users endpoint med test

2023-04-18 07:44 UTC, TereseBo commented on src/routes/authenticationRoute.js
> +} = require("../controllers/middleware/checkAuthentication");
Varför har vi lagt routen i authentication route? Den är väl inte relaterad till autentisering?

2023-04-18 07:46 UTC, andreas8151 commented on src/routes/authenticationRoute.js
> +} = require("../controllers/middleware/checkAuthentication");
vi hade skrivit att den skulle va där i trello ^^

2023-04-18 07:46 UTC, andreas8151 commented on src/routes/authenticationRoute.js
> +} = require("../controllers/middleware/checkAuthentication");
men kan flytta

2023-04-18 07:58 UTC, TereseBo commented on src/controllers/authenticationRoute/getAllUsers.js
> +    const usernames = await db.users.distinct("username");
Behöver vi verkligen ha distinct när username är indexerat, det ska ju inte vara möjligt med dubletter?

2023-04-18 07:59 UTC, TereseBo commented on src/controllers/authenticationRoute/getAllUsers.js
> +      return response.status(500).json({ error: "No users where found" });
Har vi inte använt 404 tidigare när vi har ett tomt svar?

2023-04-18 08:01 UTC, TereseBo commented on src/routes/authenticationRoute.js
> +authenticationRoute.get("/users", getAllUsers);
Placering? Andreas kollar med Metin

2023-04-18 08:03 UTC, TereseBo commented on src/routes/authenticationRoute.js
> +} = require("../controllers/middleware/checkAuthentication");
Vi hade skrivit att allt skulle vara där eftersom den authroute vi hade innebar att vi kollade kakan innan man kom åt något bakom. Det vi sedan byggde var istället att vi hade login och register där.

2023-04-18 08:05 UTC, TereseBo requested changes
Se kommentarer, avvakta svar från Metin

2023-04-18 08:15 UTC, andreas8151 commented on src/controllers/authenticationRoute/getAllUsers.js
> +      return response.status(500).json({ error: "No users where found" });
ändrat

2023-04-20 14:57 UTC, TereseBo approved these changes

2023-04-20 15:29 UTC, merged