Following route & created new file in controllers for followRoute
MikaMunterud/travelFlow-server pull request #5
Opened 2023-04-12 11:12 UTC by johanbacklin

2023-04-12 11:21 UTC, MikaMunterud requested changes
Lämnade lite kommentarer angående främst followingRoute och server.js 

Är kanske mer en bedömningsfråga på followingRoute men tänkte att server.js  behöver kolla authentication innan koden pushas till main? 😊

2023-04-12 11:21 UTC, MikaMunterud commented on src/server/server.js
Behöver man lägga till att man kolla authentication innan en användare kan följa en annan användare?

2023-04-12 11:21 UTC, MikaMunterud commented on src/routes/followingRoute.js
Är osäker, spelar det någon roll var i params man sätter :userid ? Tänker om det borde vara efter followUser/unFollowUser men kanske inte spelar någon roll.

2023-04-12 11:21 UTC, MikaMunterud commented on src/controllers/followingRoute/followUser.js
Antar att dessa är grunden utan funktion just nu? 😊

2023-04-12 11:21 UTC, MikaMunterud commented on src/controllers/followingRoute/unFollowUser.js
Antar att dessa är grunden utan funktion just nu? 😊

2023-04-12 11:34 UTC, TereseBo commented on src/server/server.js
Vi har inte byggt klart middlewaren för det än, den ligger i en egen ticket som Andreas håller på med

2023-04-12 11:55 UTC, TereseBo commented on src/routes/followingRoute.js
Kanske att vi också borde använda patch eller delete för att ta bort?

2023-04-12 12:24 UTC, johanbacklin commented on src/routes/followingRoute.js
Antingen Post eller Patch? Tror båda funkar?

2023-04-12 12:26 UTC, johanbacklin commented on src/routes/followingRoute.js
Tänker du att vi bara kör /unfollow och skippar :userId Terese?

2023-04-12 13:41 UTC, johanbacklin commented on src/routes/followingRoute.js
Okej! Tar bort det, så använder vi den där istället.

2023-04-13 05:57 UTC, TereseBo commented on src/server/server.js
Vill vi ha /followingRoute som url?

2023-04-13 07:47 UTC, johanbacklin commented on src/server/server.js
Kan ändra /following ? Kolla min senaste commits då tog jag bort userId för vi skulle använda den i req bodyn

2023-04-13 13:00 UTC, andreas8151 approved these changes

2023-04-13 13:21 UTC, MikaMunterud approved these changes

2023-04-13 13:21 UTC, merged